### ISSUE TITLE
Please support global function handler

### ISSUE THREAD

**Issue by dlydiard** [SnappyTutorials/aws-sam-webpack-plugin#13]
```
Globals:
  Function:
    Runtime: nodejs10.x
    Handler: app.handler
    MemorySize: 512
    Timeout: 30
```

Error: Endpoint is missing a Handler
